version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies for index-photos..."
      - cd lambdas/index-photos
      - pip install -r requirements.txt -t lib
      - echo "Installing dependencies for search-photos..."
      - cd ../search-photos
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package for search-photos..."
      - cd lib
      - zip -r9 ../deployment_package2.zip .
      - cd ..
      - zip -g deployment_package2.zip lambda_function.py
      - echo "Zipping deployment package for index-photos..."
      - cd ../index-photos/lib
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - zip -g deployment_package1.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating index-photos lambda Function..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_package1.zip
      - echo "Updating search-photos lambda Function..."
      - cd ../search-photos
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package2.zip
      - echo "Updating files in the S3 bucket..."
      - cd ..
      - aws s3 sync frontend/. s3://b1cloudbucket --delete
      - echo "DONE"